backend:
  name: github
  repo: SugarHyou/my-neocities-site
  branch: main

media_folder: "assets/graphics"
public_folder: "/assets/graphics"

collections:
  - name: "blurbs"
    label: "Blurb Posts"
    folder: "blurbs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { 
          label: "Category", 
          name: "category", 
          widget: "select", 
          options: ["Blurb", "Personal"] 
        }
      - { label: "Body", name: "body", widget: "markdown" }
